[package]
name = "svg-halftone"
version = "0.3.0"
authors = ["Erik Vesteraas <erik@vestera.as>"]
edition = "2018"

[dependencies]
structopt = "0.2.14"
svg-halftone-lib = { path = "svg-halftone-lib" }

[workspace]
members = [
  "svg-halftone-lib",
  "svg-halftone-wasm"
]

# Consider uncommenting before doing wasm build/deploy:
#[profile.release]
#lto = true
#opt-level = "s" # disabled due to it apparently causing bugs
