[package]
name = "svg-halftone-wasm"
version = "0.1.0"
authors = ["Erik Vesteraas <erik@vestera.as>"]
edition = "2018"
description = "WASM wrapper for svg-halftone. Creating SVG halftone patterns from raster images."
repository = "https://github.com/evestera/svg-halftone"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
cfg-if = "0.1.5"
wasm-bindgen = "0.2.68"
svg-halftone-lib = { path = "../svg-halftone-lib", features = ["wasm"] }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.5", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
wee_alloc = { version = "0.4.2", optional = true }

[features]
#default = ["console_error_panic_hook"]
default = []

# Workaround for https://github.com/rustwasm/wasm-pack/issues/886
[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz", "--enable-mutable-globals"]
